export const SUPPORTED_PLATFORMS = [
  "Agoda",
  "Airbnb",
  "AliExpress",
  "AlternativeTo",
  "Amazon",
  "Angie’s List",
  "Apartmentratings",
  "Apartments",
  "Apple Appstore",
  "Avvo",
  "BBB",
  "Bilbayt",
  "Booking.com",
  "Capterra",
  "CarGurus",
  "Cars.com",
  "Citysearch",
  "Classpass",
  "Consumer Affairs",
  "DealerRater",
  "Deliveroo",
  "Drizly",
  "eBay",
  "Edmunds",
  "Etsy",
  "Expedia",
  "Facebook",
  "FindLaw",
  "Foursquare",
  "G2",
  "Gartner",
  "Glassdoor",
  "Google",
  "Google Playstore",
  "Google Shopping",
  "Greatschools",
  "Healthgrades",
  "HomeAdvisor",
  "HomeAway",
  "Homestars",
  "Hotels.com",
  "Houzz",
  "Indeed",
  "Influenster",
  "Insider Pages",
  "IT Central Station",
  "Lawyers.com",
  "Lending Tree",
  "LinkedIn",
  "Niche",
  "OpenRice",
  "Opentable",
  "ProductHunt",
  "ProductReview.com.au",
  "RateMDs",
  "Realself",
  "ReserveOut",
  "Quartermaster",
  "Sitejabber",
  "SoftwareAdvice",
  "Talabat",
  "The Knot",
  "Thumbtack",
  "TripAdvisor",
  "Trulia",
  "TrustedShops",
  "Trustpilot",
  "Vitals",
  "Vrbo",
  "Walmart",
  "WebMD",
  "WeddingWire",
  "Yell",
  "Yelp",
  "Zillow",
  "ZocDoc",
  "Zomato",
];
