export const SELECT_PLATFORMS = "SELECT_PLATFORMS";
export const COLLECT_SURVEY = "COLLECT_SURVEY";
export const ALL_SET = "ALL_SET";
export const ONBOARDING_STEPS = [SELECT_PLATFORMS, COLLECT_SURVEY, ALL_SET];
