export const COLLECT_BUSINESS_INFO = "COLLECT_BUSINESS_INFO";
export const COLLECT_SURVEY = "COLLECT_SURVEY";
export const SELECT_PLATFORMS = "SELECT_PLATFORMS";
export const ALL_SET = "ALL_SET";
export const ONBOARDING_STEPS = [
  COLLECT_BUSINESS_INFO,
  SELECT_PLATFORMS,
  COLLECT_SURVEY,
  ALL_SET,
];
