export const LANDING_PAGE = "LANDING_PAGE";
export const COLLECT_RATING = "COLLECT_RATING";
export const SELECT_PLATFORM = "SELECT_PLATFORM";
export const ADD_NEGATIVE_FEEDBACK = "ADD_NEGATIVE_FEEDBACK";
export const POSITIVE_FEEDBACK_THANK_YOU = "POSITIVE_FEEDBACK_THANK_YOU";
export const NEGATIVE_FEEDBACK_THANK_YOU = "NEGATIVE_FEEDBACK_THANK_YOU";
export const COLLECT_CONTACT_INFO = "COLLECT_CONTACT_INFO";
