import type { Metadata } from "next";
import "./globals.css";
import { UserContext } from "@/context/userContext";
import { BusinessContext } from "@/context/businessContext";

export const metadata: Metadata = {
  title: "Rategate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <UserContext>
          <BusinessContext>{children}</BusinessContext>
        </UserContext>
      </body>
    </html>
  );
}
